export { productRouter } from "./productRouter.js"
export { cartRouter } from "./cartRouter.js"
export { productTestRouter } from "./productTestRouter.js"
export { viewsRouter } from "./viewsRouter.js"
export { sessionRouter } from "./sessionRouter.js"
export { infoRouter } from "./infoRouter.js"